ssudo: false

language: node_js

node_js:
  - "9"
  - "10"

before_script:
  - npm install codeclimate-test-reporter -g

script:
  - npm run test

after_script:
  - npm run cover
  - codeclimate-test-reporter < coverage/lcov.info

cache:
  directories:
    - node_modulesudo: false
